spring:
  application:
    name: payment
  # H2 Database 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/payment
    username: paymentuser
    password: jyoun0320@

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
    mvc:
      view:
        prefix: "/WEB-INF/views"
  imp:
    code: "imp84615760"
    api:
      key: "0614216357062647"
      secretkey: "VOvC0ZOCQVqdNv8NiDnmpRcSN61eod7mh2z8ZSgccddqNtN5NSYdHXniRxdTZlDoCcLVKR4VESPdWAlj"
  server:
    servlet:
      session:
        tracking-modes: cookie